name: test-runner
version: 0.2.0
description: A Command Line Unit Test Runner for Dart
dependencies:
  unscripted: ">=0.4.0 <0.5.0"
  ansicolor: ">=0.0.9 <0.1.0"
  yaml: ">=2.0.1+1 <3.0.0"
  path: ">=1.3.0 <2.0.0"
  coverage: ">=0.5.0 <0.6.0"
dev_dependencies:
  unittest: ">=0.11.1"
executables:
  run_tests:
