name: test_runner
version: 0.2.11+9
author: Nicolas Garnier <nivco@google.com>
description: A Command Line Test Runner for Dart
homepage: https://github.com/google/test_runner.dart
dependencies:
  unscripted: ">=0.5.0 <0.6.0"
  ansicolor: ">=0.0.9 <0.1.0"
  yaml: ">=2.0.1+1 <3.0.0"
  path: ">=1.3.0 <2.0.0"
  coverage: ">=0.5.0 <0.6.0"
  unittest: ">=0.11.4 <0.12.0"
  path: ">=1.3.0 <2.0.0"
  pool: ">=1.0.1 <2.0.0"
executables:
  run_tests:
  test_runner:
